title: My Jekyll Site
description: A static website built with Jekyll
url: "https://example.com"
markdown: kramdown
remote_theme: BDHU/minimalist
plugins:
  - jekyll-readme-index
readme_index:
  enabled:          true
  remove_originals: false
  with_frontmatter: true