title: PÃ«tr Sevostianov
description: CTO an Antilatency. Developer of Cybergaffer.


sidebar:
  - name: LinkedIn
    icon: <i class="fa-brands fa-linkedin"></i>
    link: https://www.linkedin.com/in/petr-sevostianov-67783875/
  - name: GitHub
    icon: <i class="fa-brands fa-github"></i>
    link: https://github.com/petrsevostianov

markdown: kramdown
remote_theme: BDHU/minimalist
color-scheme: light
logo: me1.png

#remote_theme: benbalter/retlab

plugins:
  - jekyll-remote-theme
  - jekyll-readme-index
readme_index:
  enabled:          true
  remove_originals: true
  with_frontmatter: true