title: My Jekyll Site
description: A static website built with Jekyll

markdown: kramdown
remote_theme: BDHU/minimalist
color-scheme: light

plugins:
  - jekyll-readme-index
readme_index:
  enabled:          true
  remove_originals: false
  with_frontmatter: true